
services:
  bot:
    build: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/ovpanel/data
      - ./backend:/ovpanel/backend
    working_dir: /ovpanel/backend 
    command: >
      bash -c "cd /ovpanel/backend &&  alembic upgrade head && python app.py"