"""added api_key for nodes

Revision ID: 89950e18b0c5
Revises: ebca6422ef3a
Create Date: 2025-09-27 23:56:47.804541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89950e18b0c5"
down_revision: Union[str, None] = "ebca6422ef3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("key", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "key")
    # ### end Alembic commands ###
