"""added settings table

Revision ID: 9710b4923333
Revises: 89950e18b0c5
Create Date: 2025-09-30 13:35:31.375096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9710b4923333"
down_revision: Union[str, None] = "89950e18b0c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tunnel_address", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_settings_id"), "settings", ["id"], unique=False)
    op.add_column("nodes", sa.Column("tunnel_address", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "tunnel_address")
    op.drop_index(op.f("ix_settings_id"), table_name="settings")
    op.drop_table("settings")
    # ### end Alembic commands ###
