"""add used traffic

Revision ID: e5dbbcdc6ef1
Revises: 2533cbca76ca
Create Date: 2026-02-26 22:39:19.138838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5dbbcdc6ef1'
down_revision: Union[str, None] = '2533cbca76ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('used', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'used')
    # ### end Alembic commands ###
